######################################################
# Secret: Create Multiples encrypted data
######################################################
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: "rootinternet-secret-{{ .Values.service.namespace }}"
spec:
  encryptedData:
    env_file: {{ .Values.safeEnvFile }}
  template:
    metadata:
      name: "rootinternet-secret-{{ .Values.service.namespace }}"
    type: Opaque